const animeData = [
  { title: "Адский рай", titleEn: "Hell's Paradise: Jigokuraku", cover: "images/hell_s_paradise_jigokuraku.jpg", rating: 4 },
  { title: "Аля иногда кокетничает со мной по-русски", titleEn: "Alya Sometimes Hides Her Feelings in Russian", cover: "images/alya_sometimes_hides_her_feelings_in_russian.jpg", rating: 3.5 },
  { title: "Ангел кровопролития", titleEn: "Angels of Death", cover: "images/angels_of_death.jpg", rating: 1.5 },
  { title: "Баскетбол Куроко", titleEn: "Kuroko's Basketball", cover: "images/kuroko_s_basketball.jpg", rating: 4 },
  { title: "Берсерк", titleEn: "Berserk", cover: "images/berserk.jpg", rating: 4.5 },
  { title: "Благоухающий цветок расцветает с достоинством", titleEn: "The Fragrant Flower Blooms with Dignity", cover: "images/the_fragrant_flower_blooms_with_dignity.jpg", rating: 3 },
  { title: "Блич", titleEn: "Bleach", cover: "images/bleach.jpg", rating: 5 },
  { title: "Евангелион", titleEn: "Neon Genesis Evangelion", cover: "images/neon_genesis_evangelion.jpg", rating: 5 },
  { title: "Эйфория", titleEn: "Euphoria", cover: "images/Euphoria.jpg", rating: 5 },
  { title: "В лес, где мерцают светлячки", titleEn: "Into the Forest of Fireflies' Light", cover: "images/into_the_forest_of_fireflies_light.jpg", rating: 2.5 },
  { title: "Ванпанчмен", titleEn: "One Punch Man", cover: "images/one_punch_man.jpg", rating: 3.5 },
  { title: "Я, владыка демонов, взял эльфийку-рабыню в жёны", titleEn: "An Archdemon's Dilemma: How to Love Your Elf Bride", cover: "images/an_archdemon_s_dilemma_how_to_love_your_elf_bride.jpg", rating: 2.5 },
  { title: "Восхождение героя щита", titleEn: "The Rising of the Shield Hero", cover: "images/the_rising_of_the_shield_hero.jpg", rating: 1 },
  { title: "Всегда вялый Танака-кун", titleEn: "Tanaka-kun is Always Listless", cover: "images/tanaka_kun_is_always_listless.jpg", rating: 3.5 },
  { title: "Голубая шкатулка", titleEn: "Blue Box", cover: "images/blue_box.jpg", rating: 3.5 },
  { title: "Город, в котором меня нет", titleEn: "Erased", cover: "images/erased.jpg", rating: 4 },
  { title: "Далёкий паладин", titleEn: "The Faraway Paladin", cover: "images/the_faraway_paladin.jpg", rating: 1.5 },
  { title: "Детектив уже мертв", titleEn: "The Detective Is Already Dead", cover: "images/the_detective_is_already_dead.jpg", rating: 2 },
  { title: "Дитя погоды", titleEn: "Weathering With You", cover: "images/weathering_with_you.jpg", rating: 2 },
  { title: "Дневник будущего", titleEn: "Future Diary", cover: "images/future_diary.jpg", rating: 3.5 },
  { title: "Добро пожаловать в класс превосходства", titleEn: "Classroom of the Elite", cover: "images/classroom_of_the_elite.jpg", rating: 3.5 },
  { title: "Дорога юности", titleEn: "Blue Spring Ride", cover: "images/blue_spring_ride.jpg", rating: 2.5 },
  { title: "Дороро", titleEn: "Dororo", cover: "images/dororo.jpg", rating: 4 },
  { title: "Меланхолия Харухи Судзумии", titleEn: "The Melancholy of Haruhi Suzumiya", cover: "images/haruhi.jpg", rating: 4 },
  { title: "Ангел по соседству", titleEn: "The Angel Next Door Spoils Me Rotten", cover: "images/the_angel_next_door_spoils_me_rotten.jpg", rating: 5 },
  { title: "Жозе, тигр и рыбы", titleEn: "Josee, the Tiger and the Fish", cover: "images/josee_the_tiger_and_the_fish.jpg", rating: 3.5 },
  { title: "Загадочная девушка X", titleEn: "X (X/1999)", cover: "images/x_x_1999.jpg", rating: 2 },
  { title: "Звёздное дитя", titleEn: "Oshi no Ko", cover: "images/oshi_no_ko.jpg", rating: 3 },
  { title: "Золотая пора", titleEn: "Golden Time", cover: "images/golden_time.jpg", rating: 3 },
  { title: "Кланнад", titleEn: "Clannad", cover: "images/clannad.jpg", rating: 5 },
  { title: "Клинок, рассекающий демонов", titleEn: "Demon Slayer: Kimetsu no Yaiba", cover: "images/demon_slayer_kimetsu_no_yaiba.jpg", rating: 4 },
  { title: "Код Гиасс", titleEn: "Code Geass: Lelouch of the Rebellion", cover: "images/code_geass_lelouch_of_the_rebellion.jpg", rating: 4.5 },
  { title: "Конец человечества", titleEn: "WorldEnd: What do you do at the end of the world? Are you busy? Will you save us?", cover: "images/worldend_what_do_you_do_at_the_end_of_the_world_are_you_busy_will_you_save_us.jpg", rating: 3 },
  { title: "Крутой учитель Онидзука", titleEn: "Great Teacher Onizuka", cover: "images/great_teacher_onizuka.jpg", rating: 5 },
  { title: "Мастера меча онлайн", titleEn: "Sword Art Online", cover: "images/sword_art_online.jpg", rating: 4.5 },
  { title: "Милый во Франксе", titleEn: "Darling in the FranXX", cover: "images/darling_in_the_franxx.jpg", rating: 4 },
  { title: "Монолог фармацевта", titleEn: "The Apothecary Diaries", cover: "images/the_apothecary_diaries.jpg", rating: 3.5 },
  { title: "Монстр за соседней партой", titleEn: "My Little Monster", cover: "images/my_little_monster.jpg", rating: 3.5 },
  { title: "Моя девушка не только милая", titleEn: "Shikimori's Not Just a Cutie", cover: "images/shikimori_s_not_just_a_cutie.jpg", rating: 3.5 },
  { title: "Не моя вина, что я не популярна!", titleEn: "No Matter How I Look at It, It's You Guys' Fault I'm Not Popular!", cover: "images/no_matter_how_i_look_at_it_it_s_you_guys_fault_i_m_not_popular.jpg", rating: 4 },
  { title: "Невиданный цветок", titleEn: "Anohana: The Flower We Saw That Day", cover: "images/anohana_the_flower_we_saw_that_day.jpg", rating: 2 },
  { title: "Обещанный Неверленд", titleEn: "The Promised Neverland", cover: "images/the_promised_neverland.jpg", rating: 3 },
  { title: "Одинокий рокер!", titleEn: "Bocchi the Rock!", cover: "images/bocchi_the_rock.jpg", rating: 3.5 },
  { title: "Маг-целитель: Новый старт", titleEn: "Redo of Healer", cover: "images/magcelitel.jpg", rating: 3.5 },
  { title: "Одноклассник", titleEn: "Doukyusei (Classmates)", cover: "images/doukyusei_classmates.jpg", rating: 2.5 },
  { title: "Оседлав волну с тобой", titleEn: "Ride Your Wave", cover: "images/ride_your_wave.jpg", rating: 2 },
  { title: "Очень приятно, Бог", titleEn: "Kamisama Kiss", cover: "images/kamisama_kiss.jpg", rating: 4 },
  { title: "Паразит: Учение о жизни", titleEn: "Parasyte -the maxim-", cover: "images/parasyte_the_maxim.jpg", rating: 4.5 },
  { title: "Песнь ночных сов", titleEn: "Call of the Night", cover: "images/call_of_the_night.jpg", rating: 3.5 },
  { title: "Пластиковые воспоминания", titleEn: "Plastic Memories", cover: "images/plastic_memories.jpg", rating: 2 },
  { title: "Поднятие уровня в одиночку", titleEn: "Solo Leveling", cover: "images/solo_leveling.jpg", rating: 4 },
  { title: "Пожиратель душ", titleEn: "Soul Eater", cover: "images/soul_eater.jpg", rating: 5 },
  { title: "Последний серафим", titleEn: "Seraph of the End", cover: "images/seraph_of_the_end.jpg", rating: 4.5 },
  { title: "Провожающая в последний путь Фрирен", titleEn: "Frieren: Beyond Journey's End", cover: "images/frieren_beyond_journey_s_end.jpg", rating: 4 },
  { title: "Путь пона", titleEn: "Pon no Michi", cover: "images/pon_no_michi.jpg", rating: 0.5 },
  { title: "Пять сантиметров в секунду", titleEn: "5 Centimeters per Second", cover: "images/5_centimeters_per_second.jpg", rating: 3 },
  { title: "Радиосигнал от чудачки", titleEn: "Ground Control to Psychoelectric Girl", cover: "images/ground_control_to_psychoelectric_girl.jpg", rating: 3.5 },
  { title: "Реинкарнация безработного", titleEn: "Mushoku Tensei: Jobless Reincarnation", cover: "images/mushoku_tensei_jobless_reincarnation.jpg", rating: 5 },
  { title: "Сага о Винланде", titleEn: "Vinland Saga", cover: "images/vinland_saga.jpg", rating: 3 },
  { title: "Связанные небом", titleEn: "Yosuga no Sora", cover: "images/yosuga_no_sora.jpg", rating: 5 },
  { title: "Синяя тюрьма: Блю Лок", titleEn: "Blue Lock", cover: "images/blue_lock.jpg", rating: 3 },
  { title: "Скажи: «Я люблю тебя»", titleEn: "Say I Love You", cover: "images/say_i_love_you.jpg", rating: 3 },
  { title: "Сквозь слёзы я притворяюсь кошкой", titleEn: "A Whisker Away", cover: "images/a_whisker_away.jpg", rating: 1 },
  { title: "Созданный в Бездне", titleEn: "Made in Abyss", cover: "images/made_in_abyss.jpg", rating: 5 },
  { title: "Счастливая звезда", titleEn: "Lucky Star", cover: "images/lucky_star.jpg", rating: 4 },
  { title: "Твоё имя", titleEn: "Your Name", cover: "images/your_name.jpg", rating: 3 },
  { title: "Тетрадь смерти", titleEn: "Death Note", cover: "images/death_note.jpg", rating: 4.5 },
  { title: "Токийские мстители", titleEn: "Tokyo Revengers", cover: "images/tokyo_revengers.jpg", rating: 5 },
  { title: "Токийский гуль", titleEn: "Tokyo Ghoul", cover: "images/tokyo_ghoul.jpg", rating: 4.5 },
  { title: "Тоннель в лето, выход прощаний", titleEn: "The Tunnel to Summer, the Exit of Goodbyes", cover: "images/the_tunnel_to_summer_the_exit_of_goodbyes.jpg", rating: 3.5 },
  { title: "Трогательный комплекс", titleEn: "Lovely Complex", cover: "images/lovely_complex.jpg", rating: 5 },
  { title: "Укрась прощальное утро цветами обещания", titleEn: "Maquia: When the Promised Flower Blooms", cover: "images/maquia_when_the_promised_flower_blooms.jpg", rating: 5 },
  { title: "Унеси меня на Луну", titleEn: "TONIKAWA: Over the Moon for You", cover: "images/tonikawa_over_the_moon_for_you.jpg", rating: 5 },
  { title: "Форма голоса", titleEn: "A Silent Voice", cover: "images/a_silent_voice.jpg", rating: 4 },
  { title: "Хантер х Хантер", titleEn: "Hunter x Hunter", cover: "images/hunter_x_hunter.jpg", rating: 5 },
  { title: "Хоримия", titleEn: "Horimiya", cover: "images/horimiya.jpg", rating: 3.5 },
  { title: "Человек-бензопила", titleEn: "Chainsaw Man", cover: "images/chainsaw_man.jpg", rating: 4 },
  { title: "Чудачества любви не помеха!", titleEn: "Love, Chunibyo & Other Delusions!", cover: "images/love_chunibyo_other_delusions.jpg", rating: 3 },
  { title: "Школьные дни", titleEn: "School Days", cover: "images/school_days.jpg", rating: 5 },
  { title: "Школьные няни", titleEn: "Gakuen Babysitters", cover: "images/gakuen_babysitters.jpg", rating: 4 },
  { title: "Эксперименты Лэйн", titleEn: "Serial Experiments Lain", cover: "images/serial_experiments_lain.jpg", rating: 4 },
  { title: "Эта фарфоровая кукла влюбилась", titleEn: "My Dress-Up Darling", cover: "images/my_dress_up_darling.jpg", rating: 2.5 },
  { title: "Этот глупый свин не понимает мечту девочки-зайки", titleEn: "Rascal Does Not Dream of Bunny Girl Senpai", cover: "images/rascal_does_not_dream_of_bunny_girl_senpai.jpg", rating: 3.5 },
  { title: "Этот замечательный мир!", titleEn: "KonoSuba: God's Blessing on This Wonderful World!", cover: "images/konosuba_god_s_blessing_on_this_wonderful_world.jpg", rating: 3.5 },
  { title: "Эхо террора", titleEn: "Terror in Resonance", cover: "images/terror_in_resonance.jpg", rating: 4 },
  { title: "Я побрился. Затем приютил старшеклассницу.", titleEn: "Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway", cover: "images/higehiro_after_being_rejected_i_shaved_and_took_in_a_high_school_runaway.jpg", rating: 2 },
  { title: "Я хочу съесть твою поджелудочную", titleEn: "I Want to Eat Your Pancreas", cover: "images/i_want_to_eat_your_pancreas.jpg", rating: 4.5 },
  { title: "Яйцо ангела", titleEn: "Angel's Egg", cover: "images/angel_s_egg.jpg", rating: 3.5 },
  { title: "Кошачий рай", titleEn: "Nekopara", cover: "images/nekopara.jpg", rating: 4 },
  { title: "Становясь волшебницей", titleEn: "Gushing over magical Girls", cover: "images/Gushing_over_Magical_Girls.jpg", rating: 4 },
  { title: "Сад изящных слов", titleEn: "The Garden of Words", cover: "images/sad_slow.jpg", rating: 4 },
  { title: "Незнакомец на берегу моря", titleEn: "The Stranger by the Shore", cover: "images/gays.jpg", rating: 2 },
  { title: "С его стороны — с её стороны", titleEn: "His and Her Circumstances", cover: "images/urme.jpg", rating: 3.5 },
  { title: "Убийца Акамэ!", titleEn: "Akame ga Kill!", cover: "images/akame.jpg", rating: 4 },
  { title: "Гуррен-Лаганн, пронзающий небеса", titleEn: "Tengen Toppa Gurren Lagann", cover: "images/gurren.jpg", rating: 4 },
  { title: "Унесённые призраками", titleEn: "Spirited Away", cover: "images/wow.jpg", rating: 4 },
];
